### ISSUE TITLE
Empty class

### ISSUE THREAD

**Issue by sda-dzarzycki** [Wojtas93/frontend#1]
https://github.com/Wojtas93/frontend/blob/21e76cb5b2d33ea5b786e5ec20be7a5d8574451d/src/app/model/user.model.ts#L1

**Comment by sda-dzarzycki** [comment]
File was included in a commit titled: "added dependencies (Bootstrap, jQuery)" (it's definetely neither of bootstrap nor jquery related)

**Comment by mdabrowski25** [comment]
Resolved in latest commit "export models of class" (done by Lukas) . That was just a folder init for dev team.
